# Generated by Django 3.2.8 on 2021-10-07 18:43

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='json',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
