# Generated by Django 3.2.8 on 2021-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_dict_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='json',
        ),
        migrations.AddField(
            model_name='dict',
            name='key',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict',
            name='value',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
