# Generated by Django 3.2.8 on 2021-10-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211007_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dates', models.TextField()),
                ('fields', models.TextField()),
                ('description', models.TextField()),
                ('size', models.TextField()),
                ('completenes', models.IntegerField()),
            ],
        ),
    ]
