# Generated by Django 3.2.8 on 2021-10-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_metafields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.TextField()),
                ('sum', models.IntegerField()),
                ('date', models.DateField()),
                ('metafields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metafields')),
            ],
        ),
    ]
