# Generated by Django 3.2.8 on 2021-10-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.TextField()),
                ('sum', models.IntegerField()),
                ('date', models.DateField()),
                ('sex', models.TextField()),
                ('age', models.IntegerField()),
                ('metafields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metafields')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('adidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adidas')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.magazine')),
                ('mts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mts')),
            ],
        ),
    ]
