# Generated by Django 3.2.8 on 2021-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_adidas_typedataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafields',
            name='payable',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafields',
            name='visible',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeDataSet',
        ),
    ]
