# Generated by Django 3.2.8 on 2021-10-09 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_metafields_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metafields',
            name='dates',
        ),
        migrations.AddField(
            model_name='metafields',
            name='date_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metafields',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
