# Generated by Django 3.2.8 on 2021-10-09 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211009_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafields',
            name='dates',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metafields',
            name='date_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='metafields',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
