# Generated by Django 3.2.8 on 2021-10-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_date_finish_metafields_dates_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metafields',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='metafields',
            name='dates_finish',
        ),
        migrations.AddField(
            model_name='metafields',
            name='date_finish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metafields',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
