# Generated by Django 3.2.8 on 2021-10-09 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211009_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafields',
            name='date_finish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='metafields',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
