# Generated by Django 3.2.8 on 2021-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20211009_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafields',
            name='type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
