# Generated by Django 3.2.8 on 2021-10-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_metafields_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteDatasets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metafields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metafields')),
            ],
        ),
    ]
